baseURL = "https://meker.xyz"
languageCode = "en-us"
title = "lanyo"
theme = "yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "lanyo"
  homepage = "https://meker.xyz/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
disqus = "joway" # disqus account name
extraHead = ''
mainSections = ["posts"]

[[params.socials]]
name = "RSS"
link = "/index.xml"

[[params.socials]]
name = "About"
link = "https://meker.xyz"
